"use client";

import {
  AlertTriangle,
  Check,
  Crown,
  Info,
  MailCheck,
  MailX,
  Pencil,
  Plus,
  ShieldCheck,
  Trash2,
  UserCog,
  Users,
  X,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { formatDisplayDateTime } from "../../lib/loader-redeem";
import styles from "./AdminPage.module.css";
import {
  ADMIN_PERM_GROUPS,
  RESELLER_PERM_GROUPS,
  defaultAdminStaffPermissions,
  defaultResellerStaffPermissions,
  normalizePermissions,
  permissionLabel,
} from "../../lib/panel-permissions";

function discordFallbackAvatarUrl(discordUserId) {
  const id = String(discordUserId || "").trim();
  if (!/^\d{17,20}$/.test(id)) return null;
  try {
    const index = Number(BigInt(id) >> 22n) % 6;
    return `https://cdn.discordapp.com/embed/avatars/${index}.png`;
  } catch {
    return null;
  }
}

export function getTransactionStaffGenerator(entry) {
  if (!entry || typeof entry !== "object") return null;
  const meta = entry.meta && typeof entry.meta === "object" ? entry.meta : {};
  const hasStaff =
    entry.actor === "reseller_staff" ||
    meta.staff_team_member_id ||
    meta.staff_discord_user_id ||
    meta.staff_discord_username;
  if (!hasStaff) return null;
  const discordUserId = meta.staff_discord_user_id || null;
  return {
    team_member_id: meta.staff_team_member_id || null,
    discord_user_id: discordUserId,
    discord_username: meta.staff_discord_username || null,
    discord_avatar_url:
      meta.staff_discord_avatar_url || discordFallbackAvatarUrl(discordUserId) || null,
    generated_at: meta.staff_generated_at || entry.created_at || null,
  };
}

export function StaffGeneratorMarker({
  generator,
  subtitle = "Generated this key",
  title = "Generated by team staff",
}) {
  const [open, setOpen] = useState(false);
  const [pos, setPos] = useState(null);
  const buttonRef = useRef(null);
  const cardRef = useRef(null);

  useEffect(() => {
    if (!open) {
      setPos(null);
      return undefined;
    }

    function updatePosition() {
      const button = buttonRef.current;
      if (!button) {
        setPos(null);
        return;
      }
      const rect = button.getBoundingClientRect();
      const cardWidth = 240;
      const gap = 8;
      const left = Math.min(rect.right + gap, window.innerWidth - cardWidth - 12);
      const top = Math.min(Math.max(12, rect.top + rect.height / 2), window.innerHeight - 12);
      setPos({ top, left: Math.max(12, left) });
    }

    function handlePointerDown(event) {
      if (cardRef.current?.contains(event.target)) return;
      if (buttonRef.current?.contains(event.target)) return;
      setOpen(false);
    }

    function handleKeyDown(event) {
      if (event.key === "Escape") setOpen(false);
    }

    updatePosition();
    window.addEventListener("resize", updatePosition);
    window.addEventListener("scroll", updatePosition, true);
    document.addEventListener("mousedown", handlePointerDown);
    document.addEventListener("keydown", handleKeyDown);
    return () => {
      window.removeEventListener("resize", updatePosition);
      window.removeEventListener("scroll", updatePosition, true);
      document.removeEventListener("mousedown", handlePointerDown);
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, [open]);

  if (!generator) return null;

  return (
    <>
      <div className={styles.licenseStaffGenWrap}>
        <button
          type="button"
          ref={buttonRef}
          className={`${styles.licenseStaffGenButton}${open ? ` ${styles.licenseStaffGenButtonOpen}` : ""}`}
          title={title}
          aria-label={title}
          aria-expanded={open}
          onClick={() => setOpen((current) => !current)}
        >
          <Users size={14} />
        </button>
      </div>
      {open && pos && typeof document !== "undefined"
        ? createPortal(
            <div
              ref={cardRef}
              className={`${styles.licenseStaffGenCard} ${styles.licenseStaffGenCardPortal}`}
              role="dialog"
              style={{ top: pos.top, left: pos.left }}
            >
              <div className={styles.licenseStaffGenCardHead}>
                {generator.discord_avatar_url ? (
                  <img
                    src={generator.discord_avatar_url}
                    alt=""
                    className={styles.licenseStaffGenAvatar}
                  />
                ) : (
                  <span className={styles.licenseStaffGenAvatarFallback} aria-hidden="true">
                    <Users size={14} />
                  </span>
                )}
                <div className={styles.licenseStaffGenMeta}>
                  <strong>{generator.discord_username || "Team staff"}</strong>
                  <span>{subtitle}</span>
                </div>
              </div>
              <div className={styles.licenseStaffGenRow}>
                <span>When</span>
                <strong>{formatDisplayDateTime(generator.generated_at)}</strong>
              </div>
              {generator.discord_user_id ? (
                <div className={styles.licenseStaffGenRow}>
                  <span>Discord ID</span>
                  <strong className={styles.teamMonoCell}>{generator.discord_user_id}</strong>
                </div>
              ) : null}
            </div>,
            document.body
          )
        : null}
    </>
  );
}

export function TeamMetaChips({
  memberCount = 0,
  memberLimit = 0,
  invitesBlocked = false,
  invitesLabel,
  role = null,
  showSecurityBadge = false,
}) {
  const inviteText =
    invitesLabel || (invitesBlocked ? "Invites blocked" : "Invites allowed");

  return (
    <div className={styles.teamMetaChips}>
      <span className={styles.teamMetaChip}>
        <Users size={13} strokeWidth={2.2} aria-hidden="true" />
        <span className={styles.teamMetaChipLabel}>Members</span>
        <strong>
          {memberCount}/{memberLimit}
        </strong>
      </span>
      <span
        className={`${styles.teamMetaChip} ${
          invitesBlocked ? styles.teamMetaChipWarn : styles.teamMetaChipOk
        }`}
      >
        {invitesBlocked ? (
          <MailX size={13} strokeWidth={2.2} aria-hidden="true" />
        ) : (
          <MailCheck size={13} strokeWidth={2.2} aria-hidden="true" />
        )}
        <span className={styles.teamMetaChipLabel}>{inviteText}</span>
      </span>
      {role === "owner" || role === "staff" ? (
        <span
          className={`${styles.teamMetaChip} ${
            role === "owner" ? styles.teamMetaChipOwner : styles.teamMetaChipStaff
          }`}
        >
          {role === "owner" ? (
            <Crown size={13} strokeWidth={2.2} aria-hidden="true" />
          ) : (
            <UserCog size={13} strokeWidth={2.2} aria-hidden="true" />
          )}
          <span className={styles.teamMetaChipLabel}>
            {role === "owner" ? "Owner access" : "Staff access"}
          </span>
        </span>
      ) : null}
      {showSecurityBadge ? (
        <span
          className={`${styles.teamMetaChip} ${styles.teamMetaChipSecurity}`}
          title="Team invites are Discord-bound. You remain responsible for members and the access you grant."
        >
          <ShieldCheck size={13} strokeWidth={2.2} aria-hidden="true" />
          <span className={styles.teamMetaChipLabel}>Digital protection</span>
        </span>
      ) : null}
    </div>
  );
}

export function PermissionDeniedToast({ message }) {
  if (!message) return null;
  return (
    <div className={styles.permissionDeniedToast} role="status" aria-live="polite">
      {message}
    </div>
  );
}

export function TeamPermissionEditor({ kind = "reseller", value, onChange, applications = [] }) {
  const groups = kind === "admin" ? ADMIN_PERM_GROUPS : RESELLER_PERM_GROUPS;
  const perms = normalizePermissions(value, kind);

  function toggle(key) {
    onChange({ ...perms, [key]: !perms[key] });
  }

  function setAppsAll(next) {
    onChange({ ...perms, "apps.all": next, "apps.ids": next ? [] : perms["apps.ids"] });
  }

  function toggleAppId(appId) {
    const id = String(appId);
    const set = new Set(perms["apps.ids"] || []);
    if (set.has(id)) set.delete(id);
    else set.add(id);
    onChange({ ...perms, "apps.all": false, "apps.ids": [...set] });
  }

  return (
    <div className={styles.teamPermEditor}>
      {groups.map((group) => (
        <div key={group.id} className={styles.teamPermGroup}>
          <strong className={styles.teamPermGroupTitle}>{group.label}</strong>
          <div className={styles.teamPermGrid}>
            {group.keys.map((key) => (
              <label
                key={key}
                className={`${styles.teamPermItem}${perms[key] ? ` ${styles.teamPermItemOn}` : ""}`}
              >
                <input type="checkbox" checked={Boolean(perms[key])} onChange={() => toggle(key)} />
                <span className={styles.teamPermCheck} aria-hidden="true">
                  {perms[key] ? <Check size={11} strokeWidth={3} /> : null}
                </span>
                <span>{permissionLabel(key)}</span>
              </label>
            ))}
          </div>
        </div>
      ))}

      <div className={styles.teamPermGroup}>
        <strong className={styles.teamPermGroupTitle}>Application access</strong>
        <label className={`${styles.teamPermItem}${perms["apps.all"] ? ` ${styles.teamPermItemOn}` : ""}`}>
          <input
            type="checkbox"
            checked={Boolean(perms["apps.all"])}
            onChange={(event) => setAppsAll(event.target.checked)}
          />
          <span className={styles.teamPermCheck} aria-hidden="true">
            {perms["apps.all"] ? <Check size={11} strokeWidth={3} /> : null}
          </span>
          <span>All applications</span>
        </label>
        {!perms["apps.all"] && applications.length ? (
          <div className={styles.teamPermGrid}>
            {applications.map((app) => {
              const id = String(app.id || app.app_id || "");
              const on = (perms["apps.ids"] || []).includes(id);
              return (
                <label key={id} className={`${styles.teamPermItem}${on ? ` ${styles.teamPermItemOn}` : ""}`}>
                  <input type="checkbox" checked={on} onChange={() => toggleAppId(id)} />
                  <span className={styles.teamPermCheck} aria-hidden="true">
                    {on ? <Check size={11} strokeWidth={3} /> : null}
                  </span>
                  <span>{app.name || id}</span>
                </label>
              );
            })}
          </div>
        ) : null}
      </div>

      <div className={styles.teamPermGroup}>
        <strong className={styles.teamPermGroupTitle}>Limits</strong>
        <div className={styles.teamLimitRow}>
          <label>
            <span>Max generate qty</span>
            <input
              type="number"
              min="1"
              max="200"
              placeholder="Unlimited"
              value={perms["limits.generate_max_qty"] ?? ""}
              onChange={(event) =>
                onChange({
                  ...perms,
                  "limits.generate_max_qty": event.target.value === "" ? null : Number(event.target.value),
                })
              }
            />
          </label>
          <label>
            <span>Generate per day</span>
            <input
              type="number"
              min="1"
              max="10000"
              placeholder="Unlimited"
              value={perms["limits.generate_per_day"] ?? ""}
              onChange={(event) =>
                onChange({
                  ...perms,
                  "limits.generate_per_day": event.target.value === "" ? null : Number(event.target.value),
                })
              }
            />
          </label>
        </div>
      </div>
    </div>
  );
}

export function TeamMemberDrawer({
  open,
  title,
  discordUserId,
  onDiscordUserIdChange,
  permissions,
  onPermissionsChange,
  kind,
  applications,
  busy,
  error,
  onClose,
  onSubmit,
  mode = "add",
}) {
  const [step, setStep] = useState("form");
  const [accepted, setAccepted] = useState(false);
  const [localError, setLocalError] = useState("");

  useEffect(() => {
    if (!open) return;
    setStep("form");
    setAccepted(false);
    setLocalError("");
  }, [open, mode, title]);

  if (!open) return null;

  const confirmTitle = mode === "add" ? "Confirm team invite" : "Confirm permission changes";
  const displayError = localError || error;

  function handleClose() {
    setStep("form");
    setAccepted(false);
    setLocalError("");
    onClose();
  }

  function handlePrimarySubmit(event) {
    event.preventDefault();
    setLocalError("");
    if (mode === "add" && !String(discordUserId || "").trim()) {
      setLocalError("Enter a valid Discord User ID.");
      return;
    }
    setAccepted(false);
    setStep("confirm");
  }

  function handleConfirmSubmit(event) {
    event.preventDefault();
    if (!accepted) {
      setLocalError("Accept the responsibility notice to continue.");
      return;
    }
    setLocalError("");
    onSubmit();
  }

  return (
    <div className={`${styles.sideDrawer} ${styles.sideDrawerOpen}`} onClick={handleClose}>
      <div
        className={`${styles.sideDrawerPanel} ${styles.sideDrawerPanelWide} ${styles.teamMemberDrawerPanel}`}
        onClick={(event) => event.stopPropagation()}
      >
        <div className={`${styles.tableHeader} ${styles.teamMemberDrawerHeader}`}>
          <h2 className={styles.noSpaceBottom}>{step === "confirm" ? confirmTitle : title}</h2>
          <button className={styles.closeButton} type="button" onClick={handleClose} aria-label="Close">
            <X size={18} />
          </button>
        </div>
        <div className={`${styles.tableContent} ${styles.teamMemberDrawerBody}`}>
          {step === "form" ? (
            <form
              className={`${styles.formPad} ${styles.teamMemberDrawerForm}`}
              onSubmit={handlePrimarySubmit}
            >
              {mode === "add" ? (
                <div className={styles.group}>
                  <label htmlFor="team-discord-user-id">Discord User ID</label>
                  <input
                    id="team-discord-user-id"
                    type="text"
                    inputMode="numeric"
                    placeholder="123456789012345678"
                    value={discordUserId}
                    onChange={(event) => onDiscordUserIdChange(event.target.value.replace(/\D/g, "").slice(0, 20))}
                    required
                  />
                </div>
              ) : null}

              <TeamPermissionEditor
                kind={kind}
                value={permissions}
                onChange={onPermissionsChange}
                applications={applications}
              />

              {displayError ? <div className={`${styles.message} ${styles.messageerror}`}>{displayError}</div> : null}

              <div className={styles.formActions}>
                <button type="button" className={styles.secondaryButton} onClick={handleClose}>
                  Cancel
                </button>
                <button type="submit" className={styles.primaryButton} disabled={busy}>
                  <Plus size={14} />
                  {mode === "add" ? "Add member" : "Save permissions"}
                </button>
              </div>
            </form>
          ) : (
            <form
              className={`${styles.formPad} ${styles.teamMemberDrawerForm} ${styles.teamMemberConfirmForm}`}
              onSubmit={handleConfirmSubmit}
            >
              <div className={styles.teamMemberLiabilityAlert} role="alert">
                <AlertTriangle size={18} aria-hidden="true" />
                <div>
                  <strong>Responsibility notice</strong>
                  <p>
                    unbanhwid.com does not accept responsibility for team members you invite, the permissions you grant
                    them, or any actions they take while using your panel access. You remain fully responsible for your
                    team, account security, and any resulting activity or abuse.
                  </p>
                </div>
              </div>

              <label
                className={`checkout-terms${accepted ? " is-checked" : ""} ${styles.teamMemberLiabilityCheck}`}
              >
                <input
                  type="checkbox"
                  checked={accepted}
                  disabled={busy}
                  onChange={(event) => {
                    setAccepted(event.target.checked);
                    if (event.target.checked) setLocalError("");
                  }}
                />
                <span className="checkout-terms-box" aria-hidden="true">
                  {accepted ? <Check size={14} strokeWidth={3} /> : null}
                </span>
                <span className="checkout-terms-text">
                  I understand and accept full responsibility for this team member and the access I grant.
                </span>
              </label>

              {displayError ? <div className={`${styles.message} ${styles.messageerror}`}>{displayError}</div> : null}

              <div className={styles.formActions}>
                <button
                  type="button"
                  className={styles.secondaryButton}
                  onClick={() => {
                    setStep("form");
                    setAccepted(false);
                    setLocalError("");
                  }}
                  disabled={busy}
                >
                  Back
                </button>
                <button type="submit" className={styles.primaryButton} disabled={busy || !accepted}>
                  <Plus size={14} />
                  {busy ? "Saving…" : mode === "add" ? "Confirm & add member" : "Confirm & save"}
                </button>
              </div>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}

export function defaultDraftPermissions(kind) {
  return kind === "admin" ? defaultAdminStaffPermissions() : defaultResellerStaffPermissions();
}

export function TeamMemberInfoDrawer({ open, member, onClose }) {
  if (!open || !member) return null;

  return (
    <div
      className={`${styles.sideDrawer} ${styles.sideDrawerOpen} ${styles.sideDrawerNested}`}
      onClick={onClose}
    >
      <div
        className={`${styles.sideDrawerPanel} ${styles.teamMemberDrawerPanel}`}
        onClick={(event) => event.stopPropagation()}
      >
        <div className={`${styles.tableHeader} ${styles.teamMemberDrawerHeader}`}>
          <h2 className={styles.noSpaceBottom}>Member information</h2>
          <button className={styles.closeButton} type="button" onClick={onClose} aria-label="Close">
            <X size={18} />
          </button>
        </div>
        <div className={`${styles.tableContent} ${styles.teamMemberDrawerBody}`}>
          <div className={styles.licenseInfoContent}>
            <div className={styles.teamInfoProfile}>
              {member.discord_avatar_url ? (
                <img
                  src={member.discord_avatar_url}
                  alt=""
                  className={styles.teamInfoAvatar}
                />
              ) : (
                <span className={styles.teamInfoAvatarFallback} aria-hidden="true">
                  <Users size={22} />
                </span>
              )}
              <div className={styles.teamInfoProfileMeta}>
                <strong>{member.discord_username || "Pending login"}</strong>
                <span>{member.status === "disabled" ? "Disabled" : "Active"}</span>
              </div>
            </div>

            <div className={styles.licenseInfoSection}>
              <h3>Discord ID</h3>
              <p className={styles.teamInfoMono}>{member.discord_user_id || "—"}</p>
            </div>
            <div className={styles.licenseInfoSection}>
              <h3>User ID</h3>
              <p className={`${styles.teamInfoMono} ${styles.appIdBlur}`}>
                {member.discord_auth_user_id || "—"}
              </p>
            </div>
            <div className={styles.licenseInfoSection}>
              <h3>Email</h3>
              <p className={`${styles.teamInfoMono} ${styles.appIdBlur}`}>
                {member.email || "—"}
              </p>
            </div>
            <div className={styles.licenseInfoSection}>
              <h3>Joined</h3>
              <p>{formatDisplayDateTime(member.created_at)}</p>
            </div>
            <div className={styles.licenseInfoSection}>
              <h3>Last updated</h3>
              <p>{formatDisplayDateTime(member.updated_at || member.created_at)}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export function TeamMembersTable({
  members,
  onEdit,
  onRemove,
  onInfo,
  layout = "full",
  busyId = "",
  actionsDenied = false,
  onDeniedClick,
}) {
  const simple = layout === "simple";

  if (!members?.length) {
    return <div className={styles.emptyState}>No team members yet.</div>;
  }
  return (
    <div className={`${styles.teamTableWrap}${simple ? ` ${styles.teamTableWrapSimple}` : ""}`}>
      <div className={styles.tableList}>
        <div className={`${styles.teamTableHeaders}${simple ? ` ${styles.teamTableSimple}` : ""}`}>
          <div>Member</div>
          {simple ? null : (
            <>
              <div>Discord ID</div>
              <div>User ID</div>
              <div>Email</div>
            </>
          )}
          <div>Actions</div>
        </div>
        {members.map((member) => (
          <div
            key={member.id}
            className={`${styles.teamTableRow}${simple ? ` ${styles.teamTableSimple}` : ""}`}
          >
            <div className={styles.teamMemberCell}>
              {member.discord_avatar_url ? (
                <img
                  src={member.discord_avatar_url}
                  alt=""
                  className={styles.teamMemberAvatarImg}
                />
              ) : (
                <span className={styles.teamMemberAvatar} aria-hidden="true">
                  <Users size={14} />
                </span>
              )}
              <strong className={styles.teamMemberName}>
                {member.discord_username || "Pending login"}
              </strong>
            </div>
            {simple ? null : (
              <>
                <div className={styles.teamMonoCell}>{member.discord_user_id || "—"}</div>
                <div className={`${styles.teamMonoCell} ${styles.appIdBlur}`}>
                  {member.discord_auth_user_id || "—"}
                </div>
                <div className={`${styles.teamMonoCell} ${styles.appIdBlur}`}>
                  {member.email || "—"}
                </div>
              </>
            )}
            <div className={`${styles.adminInlineActions} ${styles.teamActionsCell}`}>
              {typeof onInfo === "function" ? (
                <button
                  type="button"
                  className={styles.rowActionButton}
                  title="Member information"
                  aria-label="Member information"
                  onClick={() => onInfo(member)}
                  disabled={busyId === member.id}
                >
                  <Info size={15} />
                </button>
              ) : null}
              <button
                type="button"
                className={`${styles.rowActionButton}${
                  actionsDenied ? ` ${styles.rowActionButtonDenied}` : ""
                }`}
                title="Edit permissions"
                onClick={() => {
                  if (actionsDenied) {
                    onDeniedClick?.("You do not have permission to edit team members.");
                    return;
                  }
                  onEdit(member);
                }}
                disabled={busyId === member.id}
              >
                <Pencil size={15} />
              </button>
              <button
                type="button"
                className={`${styles.rowActionButton}${
                  actionsDenied ? ` ${styles.rowActionButtonDenied}` : ""
                }`}
                title="Remove"
                onClick={() => {
                  if (actionsDenied) {
                    onDeniedClick?.("You do not have permission to remove team members.");
                    return;
                  }
                  onRemove(member);
                }}
                disabled={busyId === member.id}
              >
                <Trash2 size={15} />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export function ResellerTeamPreviewDrawer({
  open,
  reseller,
  limitDraft,
  onLimitDraftChange,
  onSaveLimit,
  onEditMember,
  onRemoveMember,
  busy = false,
  busyMemberId = "",
  canEditLimits = true,
  canEditMembers = true,
  onDeniedClick,
  onClose,
}) {
  const [infoMember, setInfoMember] = useState(null);

  useEffect(() => {
    if (!open) setInfoMember(null);
  }, [open]);

  useEffect(() => {
    if (!reseller) {
      setInfoMember(null);
      return;
    }
    setInfoMember((current) => {
      if (!current?.id) return null;
      const next = (reseller.team_members || []).find((entry) => entry.id === current.id);
      return next || null;
    });
  }, [reseller]);

  if (!open || !reseller) return null;

  const activeCount = (reseller.team_members || []).filter((entry) => entry.status === "active").length;

  return (
    <>
      <div className={`${styles.sideDrawer} ${styles.sideDrawerOpen}`} onClick={onClose}>
        <div
          className={`${styles.sideDrawerPanel} ${styles.sideDrawerPanelWide} ${styles.teamPreviewDrawerPanel} ${styles.teamMemberDrawerPanel}`}
          onClick={(event) => event.stopPropagation()}
        >
          <div className={`${styles.tableHeader} ${styles.teamMemberDrawerHeader}`}>
            <h2 className={styles.noSpaceBottom}>{reseller.username || "Reseller"} team</h2>
            <button className={styles.closeButton} type="button" onClick={onClose} aria-label="Close">
              <X size={18} />
            </button>
          </div>
          <div className={`${styles.tableContent} ${styles.teamMemberDrawerBody}`}>
            <div className={`${styles.formPad} ${styles.teamMemberDrawerForm}`}>
              <div className={`${styles.teamMetaBar} ${styles.teamMetaBarAdmin}`}>
                <TeamMetaChips
                  memberCount={activeCount}
                  memberLimit={reseller.team_member_limit}
                  invitesBlocked={Boolean(reseller.team_invite_blocked)}
                />
                <div className={styles.teamMetaControls}>
                  <label className={styles.teamLimitField} htmlFor="reseller-team-limit">
                    <span>Limit</span>
                    <input
                      id="reseller-team-limit"
                      type="number"
                      min="0"
                      max="50"
                      value={limitDraft}
                      disabled={busy || !canEditLimits}
                      onChange={(event) => onLimitDraftChange(Number(event.target.value))}
                    />
                  </label>
                  <button
                    type="button"
                    className={`${styles.primaryButton} ${styles.teamLimitSaveBtn}${
                      !canEditLimits ? ` ${styles.primaryButtonDenied}` : ""
                    }`}
                    disabled={busy}
                    onClick={() => {
                      if (!canEditLimits) {
                        onDeniedClick?.("You do not have permission to change team limits.");
                        return;
                      }
                      onSaveLimit();
                    }}
                  >
                    Save limit
                  </button>
                </div>
              </div>
              <TeamMembersTable
                layout="simple"
                members={reseller.team_members || []}
                onInfo={setInfoMember}
                onEdit={onEditMember}
                onRemove={onRemoveMember}
                busyId={busyMemberId}
                actionsDenied={!canEditMembers}
                onDeniedClick={onDeniedClick}
              />
            </div>
          </div>
        </div>
      </div>
      <TeamMemberInfoDrawer
        open={Boolean(infoMember)}
        member={infoMember}
        onClose={() => setInfoMember(null)}
      />
    </>
  );
}
